# Generated by Django 2.1.4 on 2019-06-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='nickname',
        ),
    ]
