# Generated by Django 2.1.4 on 2019-05-22 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '草稿')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='正文支持MarkDown格式', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 22, 7, 54, 222477), verbose_name='创建时间'),
        ),
    ]
