# Generated by Django 2.1.4 on 2019-05-23 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190522_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文markdown转的html内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 10, 36, 32, 907837), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '发布'), (0, '草稿')], default=1, verbose_name='状态'),
        ),
    ]
