# Generated by Django 2.1.4 on 2019-05-23 03:15

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190523_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_html',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='正文支持MarkDown格式', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 11, 15, 34, 708243), verbose_name='创建时间'),
        ),
    ]
