# Generated by Django 2.1.4 on 2019-06-01 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190523_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.SmallIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 12, 43, 7, 909765), verbose_name='创建时间'),
        ),
    ]
