# Generated by Django 2.1.4 on 2019-06-01 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190601_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='点赞IP')),
            ],
            options={
                'verbose_name': '点赞IP库',
                'verbose_name_plural': '点赞IP库',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 14, 54, 37, 877396), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_ip',
            field=models.ManyToManyField(to='blog.LikeIp', verbose_name='点赞IP'),
        ),
    ]
