# Generated by Django 2.1.4 on 2019-06-01 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190601_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_ip',
        ),
        migrations.AddField(
            model_name='likeip',
            name='like_article',
            field=models.ManyToManyField(to='blog.Article', verbose_name='点赞文章'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 15, 43, 37, 347527), verbose_name='创建时间'),
        ),
    ]
